/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.fs.maintenance.gui;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import org.fs.maintenance.common.Pair;
import org.fs.maintenance.entities.Department;
import org.fs.maintenance.utils.StringUtility;

/**
 *
 * @author Fatih
 */
public class DepartmentTaskCell extends javax.swing.JPanel implements ListCellRenderer<Pair<Department, Integer>>{

    /**
     * Creates new form DepartmentTaskCell
     */
    private DepartmentTaskCell() {
        initComponents();
        init();
    }

    public static DepartmentTaskCell createView() {
        return new DepartmentTaskCell();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDeparmentName = new javax.swing.JLabel();
        lblNumberOfTaskCreated = new javax.swing.JLabel();

        lblDeparmentName.setText("jLabel1");

        lblNumberOfTaskCreated.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDeparmentName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNumberOfTaskCreated)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeparmentName)
                    .addComponent(lblNumberOfTaskCreated))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDeparmentName;
    private javax.swing.JLabel lblNumberOfTaskCreated;
    // End of variables declaration//GEN-END:variables
    
    private Color firstColor;
    private Color secondColor;
    
    private void init() {
        firstColor = StringUtility.hex2Rgb(StringUtility.FIRST_COLOR_STR);
        secondColor = StringUtility.hex2Rgb(StringUtility.SECOND_COLOR_STR);
    }
    
    @Override
    public Component getListCellRendererComponent(JList<? extends Pair<Department, Integer>> list, Pair<Department, Integer> value, int index, boolean isSelected, boolean cellHasFocus) {
        if(index == 0) {
            lblDeparmentName.setText("DEPARTMENT NAME");
            lblNumberOfTaskCreated.setText("NUMBER OF TASKS CREATED");
            setBackground(StringUtility.hex2Rgb(StringUtility.SELECTED_COLOR_STR));
            
        } else {        
            lblDeparmentName.setText(value.getKey().getDepartmentName());
            lblNumberOfTaskCreated.setText(String.valueOf(value.getValue()));
            boolean mod = index % 2 == 0;
            if(mod) {
                setBackground(firstColor);
            } else {
                setBackground(secondColor);
            }   
        }
        return this;
    }
}
