/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.fs.maintenance.gui;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import org.fs.maintenance.entities.Employee;
import org.fs.maintenance.utils.StringUtility;

/**
 *
 * @author Fatih
 */
public class EmployeeBox extends javax.swing.JPanel implements ListCellRenderer<Employee>{

    /**
     * Creates new form EmployeeBox
     */
    public EmployeeBox() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmployeeID = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();

        lblEmployeeID.setText("jLabel1");

        lblEmployeeName.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmployeeID)
                .addGap(18, 18, 18)
                .addComponent(lblEmployeeName, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblEmployeeName)
                .addComponent(lblEmployeeID))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEmployeeName;
    // End of variables declaration//GEN-END:variables
    
    private Color firstColor;
    private Color secondColor;
    private Color selectedColor;
    
    private void init() {
        firstColor = StringUtility.hex2Rgb(StringUtility.FIRST_COLOR_STR);
        secondColor = StringUtility.hex2Rgb(StringUtility.SECOND_COLOR_STR);
        selectedColor = StringUtility.hex2Rgb(StringUtility.SELECTED_COLOR_STR);         
    }
    
    @Override
    public Component getListCellRendererComponent(JList<? extends Employee> list, Employee value, int index, boolean isSelected, boolean cellHasFocus) {
        lblEmployeeID.setText(String.valueOf(value.getId()));
        lblEmployeeName.setText(value.getName());
        if(isSelected) {
            setBackground(selectedColor);
        } else {
            boolean mod = index % 2 == 0;
            if(mod) {
                setBackground(firstColor);
            } else {
                setBackground(secondColor);
            }                        
        }        
        return this;
    }
}
