/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.fs.maintenance.gui;

import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import org.fs.maintenance.common.*;
import org.fs.maintenance.entities.Employee;
import org.fs.maintenance.utils.StringUtility;

/**
 *
 * @author Fatih
 */
public class ListEmployeeCell extends javax.swing.JPanel implements ListCellRenderer<Employee> {

    /**
     * Creates new form ListEmployeeCell
     */
    private ListEmployeeCell() {
        initComponents();
        init();
    }
    
    public static ListEmployeeCell createView() {
        return new ListEmployeeCell();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmployeeID = new javax.swing.JLabel();
        lblNumberOfTasks = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        lblEmployeeSurname = new javax.swing.JLabel();

        lblEmployeeID.setText("jLabel1");
        lblEmployeeID.setMaximumSize(new java.awt.Dimension(32, 16));
        lblEmployeeID.setMinimumSize(new java.awt.Dimension(32, 16));
        lblEmployeeID.setPreferredSize(new java.awt.Dimension(32, 16));

        lblNumberOfTasks.setText("jLabel2");
        lblNumberOfTasks.setMaximumSize(new java.awt.Dimension(32, 16));
        lblNumberOfTasks.setMinimumSize(new java.awt.Dimension(32, 16));
        lblNumberOfTasks.setPreferredSize(new java.awt.Dimension(32, 16));

        lblEmployeeName.setText("jLabel3");
        lblEmployeeName.setMaximumSize(new java.awt.Dimension(120, 16));
        lblEmployeeName.setMinimumSize(new java.awt.Dimension(120, 16));
        lblEmployeeName.setPreferredSize(new java.awt.Dimension(120, 16));

        lblEmployeeSurname.setText("jLabel4");
        lblEmployeeSurname.setMaximumSize(new java.awt.Dimension(120, 16));
        lblEmployeeSurname.setMinimumSize(new java.awt.Dimension(120, 16));
        lblEmployeeSurname.setPreferredSize(new java.awt.Dimension(120, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumberOfTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmployeeSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumberOfTasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmployeeSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblEmployeeSurname;
    private javax.swing.JLabel lblNumberOfTasks;
    // End of variables declaration//GEN-END:variables
    
    private Color firstColor;
    private Color secondColor;
    private Color selectedColor;
    
    private IDatabaseManager dbManager;
    
    private void init() {
        firstColor = StringUtility.hex2Rgb(StringUtility.FIRST_COLOR_STR);
        secondColor = StringUtility.hex2Rgb(StringUtility.SECOND_COLOR_STR);
        selectedColor = StringUtility.hex2Rgb(StringUtility.SELECTED_COLOR_STR); 
        dbManager = DatabaseManager.getSharedInstance();
    }

    @Override
    public Component getListCellRendererComponent(JList<? extends Employee> list, Employee value, int index, boolean isSelected, boolean cellHasFocus) {
        try {
            int numberOfTasks = dbManager.calculateNumberOfTasksAssignedToItEmployee(value);
            
            lblEmployeeID.setText(String.valueOf(value.getId()));
            lblNumberOfTasks.setText(String.valueOf(numberOfTasks));
            lblEmployeeName.setText(value.getName());
            lblEmployeeSurname.setText(value.getSurname());
            
            if(isSelected) {
                setBackground(selectedColor);
            } else {
                boolean mod = index % 2 == 0;
                if(mod) {
                    setBackground(firstColor);
                } else {
                    setBackground(secondColor);
                }                        
            }
            
        } catch(SQLException e) {
            throw new RuntimeException(e);
        }
        return this;
    }
}


