/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.fs.maintenance.gui;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import org.fs.maintenance.entities.TaskStatus;
import org.fs.maintenance.utils.StringUtility;

/**
 *
 * @author Fatih
 */
public class TaskStatusBox extends javax.swing.JPanel implements ListCellRenderer<TaskStatus>{

    /**
     * Creates new form TaskStatusBox
     */
    private TaskStatusBox() {
        initComponents();
        init();
    }
    
    public static TaskStatusBox createView() {
        return new TaskStatusBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatus = new javax.swing.JLabel();

        lblStatus.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStatus)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStatus)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
   
    private Color firstColor;
    private Color secondColor;
    private Color selectedColor;
    
    private void init() {
        firstColor = StringUtility.hex2Rgb(StringUtility.FIRST_COLOR_STR);
        secondColor = StringUtility.hex2Rgb(StringUtility.SECOND_COLOR_STR);
        selectedColor = StringUtility.hex2Rgb(StringUtility.SELECTED_COLOR_STR);        
    }
    
    @Override
    public Component getListCellRendererComponent(JList<? extends TaskStatus> list, TaskStatus value, int index, boolean isSelected, boolean cellHasFocus) {
        lblStatus.setText(value.toString());
        if(isSelected) {
            setBackground(selectedColor);
        } else {
            boolean mod = index % 2 == 0;
            if(mod) {
                setBackground(firstColor);
            } else {
                setBackground(secondColor);
            }                        
        }        
        return this;
    }
}
